Add type to ref_data_hla_slice_bed entry in the nextflow_schema.json
nf-core/oncoanalyser pull request #96
Opened 2024-09-09 12:22 UTC by scoughlan2

This adds a missing type field, as outlined in issue [#93](https://github.com/nf-core/oncoanalyser/issues/93), to an entry in the nextflow_schema.json

Hopefully I have done the change/pull request correctly this time! Thanks!

## PR checklist

- [x ] This comment contains a description of changes (with reason).

2024-09-09 23:05 UTC, scwatts approved these changes

2024-09-09 23:12 UTC, scwatts requested changes
Could you please include an entry in the CHANGELOG.md file too? See here for an example:

https://github.com/nf-core/oncoanalyser/blob/a9b94fadcd0622603287da2f3b49629baae9f74e/CHANGELOG.md?plain=1#L8

2024-09-10 10:54 UTC, scoughlan2 commented
Done, thanks. 

> Could you please include an entry in the CHANGELOG.md file too? See here for an example:
> 
> https://github.com/nf-core/oncoanalyser/blob/a9b94fadcd0622603287da2f3b49629baae9f74e/CHANGELOG.md?plain=1#L8

2024-09-10 23:16 UTC, scwatts approved these changes

2024-09-11 23:06 UTC, merged